### ISSUE TITLE
Queue VisibilityTimeouts are not respected

### ISSUE THREAD

**Issue by awwalker** [RutledgePaulV/piped#12]
We recently ran into an issue where a long running message was almost double processed:
```
Jan 05 11:31:40.695
i-0937b56a787de8a00
core
Error extending visibility timeout of inflight message. {:ErrorResponse {:Error {:Type "Sender", :TypeAttrs {}, :Code "InvalidParameterValue", :CodeAttrs {}, :Message "Value AQEB2+gMX4gSZTJXFdycDOyV1OaMnVqSPctWcTxh3wEkuI3jFVLOv3c27SSh01s9+te3AFF001oiGvhsIavSa5zoCpvO3wZ3jESPHVWDn4125iLwIxX849Nfln8QaWe1v2aF1h39fqDe8SmFfXwja6vYkXAB9gAAxdxHhkylBjzbD7dlNN/7d6mQaaHIMYQRItdB8ovz1zFJvB+A7ER9L1lXpI07DA/JveLraR1+b33rZGBG4hng3UdwVbQro7QBXRBeD4ZGyp/nNcSnNNoG+LzLOCwwplEU9Bj6emv3x6YzZx8= for parameter ReceiptHandle is invalid. Reason: The receipt handle has expired.", :MessageAttrs {}, :Detail nil, :DetailAttrs {}}, :ErrorAttrs {}, :RequestId "6b120323-726b-58fc-b388-5d3143478cd7", :RequestIdAttrs {}}, :ErrorResponseAttrs {:xmlns "http://queue.amazonaws.com/doc/2012-11-05/"}, :cognitect.aws.http/status 400, :cognitect.anomalies/category :cognitect.anomalies/incorrect, :cognitect.aws.error/code "InvalidParameterValue"}

Jan 05 11:31:40.687
i-0937b56a787de8a00
core
core.services.ach.processor-scheduling/find-aligned-window-and-upcoming-ledger-window-sqs
[IdempotentOp] already set: :ach-ledger-window-process 202401051630:core_fifththird_fifththird:1200::standard

Jan 05 11:31:40.686
i-0937b56a787de8a00
core
core.services.ach.processor-scheduling/find-aligned-window-and-upcoming-ledger-window-sqs
ACH ledger window processor running

...


Jan 05 11:30:40.653
i-0937b56a787de8a00
core
Extended visibility for inflight message 27cb84a3-2299-44cf-b1ae-88501a813e50 in queue https://sqs.us-west-2.amazonaws.com/181336694045/staging_default.fifo from 30 to 60 seconds.
```

Our logs suggest that the first attempt at a VisibilityTimeout increase was successful, however this bump should not have happened. The queue these messages were in have a default VisibilityTimeout of 5 minutes, not 30 seconds. I think the issue is [here](https://github.com/awwalker/piped/blob/4eb98e7bb75e09a01f25865df665ed37ac80bb5b/src/piped/producers.clj#L31) and [here](https://github.com/awwalker/piped/blob/4eb98e7bb75e09a01f25865df665ed37ac80bb5b/src/piped/producers.clj#L44).

The original request for messages is setting the VisibilityTimeout for the messages received to 30 seconds. And then piped is setting up internal timeouts also for 30 seconds. 

I think Piped should [ping the queue](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html) for the VisibilityTimeout and only fallback to this 30 seconds default if one does not exist on the queue.

**Comment by RutledgePaulV** [comment]
changes released as 0.1.10, thanks for the contribution!
